version: "3.1"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/app
            - ./logs/nginx:/logs/nginx
            - ./docker/config/nginx/xdebug:/etc/nginx/xdebug
            - ./docker/config/nginx/hosts:/etc/nginx/hosts
            - ./docker/config/nginx/init.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/app
        networks:
            - php-network
        links:
          - php
          - mysql
    php:
        build:
            dockerfile: Dockerfile
            context: ./docker/php/
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/app
            - ./logs/xdebug:/logs/xdebug
            - ./docker/config/php/custom.conf:/usr/local/etc/php-fpm.d/zz-custom.conf
            - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
            - ./logs/php-fpm/:/tmp/xdebug_log
        working_dir: /var/www/app
        networks:
            - php-network
        links:
            - mysql
        
    mysql:
        image: "mysql:5.7"
        ports:
        - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            - php-network
    node:
        image: node:16
        working_dir: /app
        volumes:
        - ./app:/app
        tty: true
        command: ["npm","install"]

    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ici-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        ports:
        - "8080:80"
        depends_on:
        - mysql
        networks:
        - php-network

#
networks:
    php-network:
        driver: bridge
